<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>service score</name>
  <uuid>b808370b-3f46-41fc-943c-f7df15e52b2b</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
the number of elements in the Services requested of Services is more than 3
then
add 1 to decision ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
